### ISSUE TITLE
templateId not documented 

### ISSUE THREAD

**Issue by Heaven4All** [fortify-ps/fortify-ssc-parser-util#3]
Hi .

Where we are able to find information about the templateId to know what are the options we can use in viewtemplate json file ?

Regards,
Kirk

**Comment by rsenden** [comment]
Official documentation about the SSC parser plugin API, including information about the view template JOSN, can be found at https://github.com/fortify/sample-parser.

Note that the fortify-ps/fortify-ssc-parser-util project (and all other projects under github.com/fortify-ps) are not officially supported through the regular Fortify support channels, may not be regularly maintained, and do not follow the Micro Focus quality assurance standards. 

You are free to use these projects as you see fit; fortify-ssc-parser-util greatly simplifies development of parsers for XML or JSON data and I have used it for many parser implementations. However you should be aware that the API may change without notice in future versions, and support and maintenance is provided on a best-effort basis or through paid Professional Services engagements.
